### ISSUE TITLE
how do i put a font? 

### ISSUE THREAD

**Issue by Pqoh** [AKORA-Studios/DiscordWelcomeCard#26]
my attempt: 
```
...
text: {
              title: new Text('Welcome to my guild!', 220, 80).setFontSize(40).setFont('Heartless.ttf'),
...
```

**Comment by A-K-O-R-A** [comment]
You need to register the Font before using it, this can be done by the `registerFont` method from which is provided by canvas out of the box.
```js
const { join } = require('path')
const { registerFont } = require('canvas')

registerFont(join(__dirname, '../path/to/font.ttf'), { family: 'FontName' });
```

In order to use the font with the package you just need to call the method `.setFont` as you did before but instead just do `.setFont('FontName')`

Note:
You should change `FontName` according to the name of your font.
And `../path/to/font.ttf` to the path of your font, relative to the current file you are writing in.

**Comment by A-K-O-R-A** [comment]
If you don't have any further I will close this issue in 3 days.
